extends: airbnb

env:
  browser: true
  node: true

plugins: ['html']

rules:
  no-underscore-dangle: 0
  prefer-destructuring: 0
  no-param-reassign: 0
  arrow-parens: 0
  comma-dangle: 0
  operator-linebreak: 0
  no-plusplus: 0
